/*
 * FROZEN snapshot of the build-info v1 API surface (ABI v7,
 * CAPSID_BUILD_INFO_VERSION 1), captured for the WP-07 size-negotiation
 * test (spec §11.4): a caller compiled against these OLD headers must
 * link against the CURRENT library and negotiate successfully with its
 * smaller struct_size.
 *
 * Do NOT edit this file to track runtime.h — it is a fixture on purpose.
 * It mirrors include/capsid/runtime.h as it was before WP-07 appended the
 * provenance fields: the same capsid_build_info layout through
 * compatibility_id, CAPSID_BUILD_INFO_VERSION 1, and the same result
 * enumerators the test relies on.
 */
#ifndef CAPSID_FIXTURE_RUNTIME_BUILD_INFO_V1_H
#define CAPSID_FIXTURE_RUNTIME_BUILD_INFO_V1_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define CAPSID_BUILD_INFO_VERSION 1u

typedef enum capsid_result {
    CAPSID_OK = 0,
    CAPSID_WOULD_BLOCK = 1,
    CAPSID_CLOSED = 2,
    CAPSID_INVALID_ARGUMENT = 3,
    CAPSID_PROTOCOL_ERROR = 4,
    CAPSID_SYSTEM_ERROR = 5,
    CAPSID_CHILD_ERROR = 6
} capsid_result;

typedef struct capsid_build_info {
    uint32_t struct_size;
    uint32_t version;
    const char *runtime_version;
    uint32_t abi_version;
    uint32_t fetchrpc_version;
    const char *quickjs_commit;
    const char *txiki_overlay_key;
    const char *txiki_overlay_manifest;
    const char *bytecode_compile_flags;
    const char *target_architecture;
    const char *endianness;
    uint32_t pointer_width_bits;
    const char *bytecode_format_identity;
    const char *capability_manifest_sha256;
    const char *compatibility_id;
} capsid_build_info;

void capsid_build_info_init(capsid_build_info *info);
capsid_result capsid_runtime_build_info(capsid_build_info *out_info);

#ifdef __cplusplus
}
#endif

#endif /* CAPSID_FIXTURE_RUNTIME_BUILD_INFO_V1_H */
